name: Software Composition Analysis (SCA)

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        id: generate-sbom
        with:
          path: .
          output-file: sbom.json
          format: syft-json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  scan-sbom:
    name: Scan SBOM with Grype
    needs: generate-sbom
    runs-on: ubuntu-latest
    steps:
      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom

      - name: Scan SBOM with Grype
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.json
          severity-cutoff: critical  # Modifier ici pour accepter les vulnérabilités de niveau high et plus
