name: HadoLint

on:
  push:
    branches: [ main, feature/cicd_setup ]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'

jobs:
  lint-dockerfile:
    name: Lint Dockerfile with Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
