name: Run Unit Tests

on: [push, pull_request]

jobs:
  integration-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
      - name: Run unit tests
        run: |
          pytest unit_tests --disable-warnings --maxfail=1 --tb=short --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing